### ISSUE TITLE
dependecies.yaml is order dependant

### ISSUE THREAD

**Issue by michaelschiff** [johnynek/bazel-deps#109]
Dependency processing seems to be dependent on the ordering of items in the dependencies yaml file.

Example:
```
dependencies:
  org.springframework:
    spring-beans:
      version: "4.2.1.RELEASE"
      lang: java
  org.springframework:
    spring-context:
      version: "4.2.1.RELEASE"
      lang: java
  org.springframework:
    spring-core:
      version: "4.2.1.RELEASE"
      lang: java
```
produces the following in 3rdparty/jvm/org/springframework/BUILD 
```
java_library(
    name = "spring_core",
    exports = [
        "//3rdparty/jvm/commons_logging:commons_logging",
        "//external:jar/org/springframework/spring_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)
```

If I re-order the yaml file as follows (moving spring-core artifact to be listed first):
```
dependencies:
  org.springframework:
    spring-core:
      version: "4.2.1.RELEASE"
      lang: java
  org.springframework:
    spring-beans:
      version: "4.2.1.RELEASE"
      lang: java
  org.springframework:
    spring-context:
      version: "4.2.1.RELEASE"
      lang: java
```

then the following is generated in 3rdparty/jvm/org/springframework/BUILD
```
java_library(
    name = "spring_aop",
    exports = [
        "//3rdparty/jvm/aopalliance:aopalliance",
        "//external:jar/org/springframework/spring_aop"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "spring_beans",
    exports = [
        "//external:jar/org/springframework/spring_beans"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "spring_context",
    exports = [
        "//external:jar/org/springframework/spring_context",
        ":spring_aop",
        ":spring_beans",
        ":spring_core",
        ":spring_expression"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "spring_core",
    exports = [
        "//3rdparty/jvm/commons_logging:commons_logging",
        "//external:jar/org/springframework/spring_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "spring_expression",
    exports = [
        "//external:jar/org/springframework/spring_expression"
    ],
    visibility = [
        "//visibility:public"
    ]
)
```

**Comment by johnynek** [comment]
yaml is order dependent. You are overwriting keys in the yaml.

you should write:
```
dependencies:
  org.springframework:
    spring-beans:
      version: "4.2.1.RELEASE"
      lang: java

    spring-context:
      version: "4.2.1.RELEASE"
      lang: java

    spring-core:
      version: "4.2.1.RELEASE"
      lang: java
```
or more compactly:
```
dependencies:
  org.springframework:
    spring:
      version: "4.2.1.RELEASE"
      modules: [beans, context, core]
      lang: java
```
