### ISSUE TITLE
Support packaging types: jar, war, aar, bundle, and so on

### ISSUE THREAD

**Issue by jin** [johnynek/bazel-deps#119]
Maven assumes `jar` by default [1]. https://maven.apache.org/pom.html#Maven_Coordinates 

I propose that a new `packaging` field to be added as a child of `artifactId`, like so:

```
com.android.support.espresso:
  espresso-core:
    packaging: aar
    lang: java
    version: "3.0.0"
```

If `packaging` is not specified, it will default to `jar`. This will unblock AAR support (#80).

I have a WIP commit here with passing tests: https://github.com/jin/bazel-deps/commit/ca00e226df2c74d5b515ea45c611ad5abb0e3fde#diff-ba7bf4242651f01e4c2b3dd54e4c3bbbR38
