### ISSUE TITLE
Parse error for javax.servlet:servlet-api:2.5 dependency 

### ISSUE THREAD

**Issue by namtzigla** [johnynek/bazel-deps#127]
I have in my dependency file the following:
```
dependencies:
  javax.servlet:
    servlet-api:
      version: 2.5
      lang: java
```

When I'm trying to generate bazel deps I'm getting the following error:
```
[ERROR]: Failed to parse dependencies.yaml.
DecodingFailure(String, List(DownField(version), DownField(servlet-api), DownField(javax.servlet), DownField(dependencies)))
```
Is there a reason for this?

**Comment by promiseofcake** [comment]
Version should be quoted as:
```
dependencies:
  javax.servlet:
    servlet-api:
      version: "2.5"
      lang: java
```
