### ISSUE TITLE
format-deps strips out comments

### ISSUE THREAD

**Issue by vmax** [johnynek/bazel-deps#137]
This:

```
options:
  # one comment
  languages: [ "java" ]
  licenses: [ "permissive" ]
  resolvers: 
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
  thirdPartyDirectory: "third_party/maven/"
  transitivity: runtime_deps
  versionConflictPolicy: highest

dependencies:
  # another one
  org.slf4j:
    slf4j-simple:
      lang: java
      version: "1.7.25"
```

turns into this:

```
options:
  languages: [ "java" ]
  licenses: [ "permissive" ]
  resolvers: 
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
  thirdPartyDirectory: "third_party/maven/"
  transitivity: runtime_deps
  versionConflictPolicy: highest

dependencies:
  org.slf4j:
    slf4j-simple:
      lang: java
      version: "1.7.25"
```

Could you please either fix the behaviour or warn that comments were lost?
