### ISSUE TITLE
`modules: [ "" ]` doesn't play nice with exports

### ISSUE THREAD

**Issue by roblg** [johnynek/bazel-deps#138]
The following `dependencies` section results in an error when running the `generate` command:

```
  org.apache.httpcomponents:
    httpclient:
      exports:
        - "org.apache.httpcomponents:httpcore"
      lang: java
      version: "4.5.2"
    httpcore:
      lang: java
      modules: [ "", "nio" ]
      version: "4.4.4"
```

Error:
```
Could not find explicit exports named by: UnversionedCoordinate(MavenGroup(org.apache.httpcomponents),MavenArtifactId(httpclient))
```

Breaking up the `httpcore` single entry into `httpcore` and `httpcore-nio` separately resolves the issue.
