### ISSUE TITLE
optional dependencies of required dependencies are always imported

### ISSUE THREAD

**Issue by kevingessner** [johnynek/bazel-deps#155]
Per 9868da9d6ee6a94b96dcc470161fad55985725b1, it appears the expected behavior of bazel-deps is to exclude optional dependencies unless they are explicitly exported.  That's a good default but I'm not seeing it take effect in every case.  In particular, it appears that if dependency A requires dependency B, all of B's optional dependencies are included by bazel-deps.  If A is not included and B is used directly by bazel-deps, B's optional dependencies are not included.

These `dependencies.yaml` examples show the problem, repro'd at f5cb5823409a8b2773fa719deb5afc15a3a83425.

```yaml
dependencies:
  org.apache.logging.log4j:
    log4j:
      lang: java
      modules: [ "core" ]
      version: "2.8.2"
```

Running `generate` on this file correct produces a BUILD file with just `log4j-core` and it's required dependency `log4j-api` ([pom](http://central.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.8.2/log4j-core-2.8.2.pom)):

```
> bazel query //...
//3rdparty/jvm/org/apache/logging/log4j:log4j_core
//3rdparty/jvm/org/apache/logging/log4j:log4j_api
```

However, adding `log4j-1.2-api` and running generate again produces a much larger set of dependencies:

```yaml
dependencies:
  org.apache.logging.log4j:
    log4j:
      lang: java
      modules: [ "1.2-api", "core" ]
      version: "2.8.2"
```

```
> bazel query //...
.............
//3rdparty/jvm/org/apache/logging/log4j:log4j_1_2_api
//3rdparty/jvm/org/apache/logging/log4j:log4j_core
//3rdparty/jvm/org/zeromq:jeromq
//3rdparty/jvm/org/jctools:jctools_core
//3rdparty/jvm/org/apache/logging/log4j:log4j_api
//3rdparty/jvm/org/apache/kafka:kafka_clients
//3rdparty/jvm/org/xerial/snappy:snappy_java
//3rdparty/jvm/org/apache/commons:commons_csv
//3rdparty/jvm/org/apache/commons:commons_compress
//3rdparty/jvm/net/jpountz/lz4:lz4
//3rdparty/jvm/com/sun/mail:javax_mail
//3rdparty/jvm/javax/activation:activation
//3rdparty/jvm/com/lmax:disruptor
//3rdparty/jvm/com/conversantmedia:disruptor
//3rdparty/jvm/org/slf4j:slf4j_api
```

These are not dependencies of `log4j-1.2-api` ([pom](http://central.maven.org/maven2/org/apache/logging/log4j/log4j-1.2-api/2.8.2/log4j-1.2-api-2.8.2.pom)) but are optional dependencies of `log4j-core`.  bazel-deps is treating them as required and including them, which it didn't before.

I'm not sure why bazel-deps is doing this but it seems wrong.  Optional transitive dependencies should remain optional.
