### ISSUE TITLE
Questions: scala/unmangled and options meaning

### ISSUE THREAD

**Issue by jmendiara** [johnynek/bazel-deps#169]
First of all, I'm pretty new to scala and bazel, and maybe those questions seems obvious, but by reading the readme, I dont get the point about `scala/unmangled`  ¯\_(ツ)_/¯

> Language is always required and may be one of java, scala, scala/unmangled

later on `dependencies.yml` 
```yml
replacements:
  org.scala-lang:
    scala-library:
      lang: scala/unmangled # scala-library is not mangled like sbt does with other jars
```

**What does it mean `scala/unmangled` and what are the differences with `scala`?**

I understand the examples about _replacements_ but i miss something about `unmangled` 

---

In https://github.com/johnynek/bazel-deps#options you say
> languages: java and scala

But setting `scala` as options does not work. in your `dependencies.yml` there is `scala:2.11.8` 
https://github.com/johnynek/bazel-deps/blob/master/dependencies.yaml#L3

**What is the purpose of `languages` option what does it do?**

> transitivity: runtime_deps or exports

**What are the differences between transitivity values?**

Thanks guys, this project simplifies a lot the bazel usage!
