### ISSUE TITLE
Populate licenses on replacements

### ISSUE THREAD

**Issue by bjchambers** [johnynek/bazel-deps#188]
When using a library such as protocol buffers, it is common to do something like:

In workspace:

```
http_archive(
    name = "com_google_protobuf",
    sha256 = "cef7f1b5a7c5fba672bec2a319246e8feba471f04dcebfe362d55930ee7c1c30",
    strip_prefix = "protobuf-3.5.0",
    urls = ["https://github.com/google/protobuf/archive/v3.5.0.zip"],
)
```

Elsewhere, the `deps` then need to use `@com_google_protobuf//:protobuf_java`. To ensure that any JARs retrieved from Maven use the same version, it makes sense to add something like this to dependencies.yaml:

```
replacements:
  com.google.protobuf:
    protobuf-java:
      lang: java
      target: "@com_google_protobuf//:protobuf_java"
```

This works, however it seems awkward that within my project I must use `@com_google_protobuf//:protobuf_java` when there is a file at `//3rdparty/com/google/protobuf:protobuf-java` that is perfectly useable, except it doesn't have the appropriate licenses to be usable. Could the BUILD file entries generated for replacements support the same licenses setting?
