### ISSUE TITLE
Artifacts in replacements shouldn't need versions

### ISSUE THREAD

**Issue by bjchambers** [johnynek/bazel-deps#194]
Say that GRPC is loaded as a replacement, with something like:

```
replacements:
  io.grpc:
    grpc-core:
      lang: java
      target: "@io_grpc_grpc_java//core"
    grpc-netty:
      lang: java
      target: "@io_grpc_grpc_java//netty"
    grpc-stub:
      lang: java
      target: "@io_grpc_grpc_java//stub"
```

If we want to depend on that outside of third party, we need to change the visibility rule. This can be done by listing these artifacts in the main `dependencies` section as well. However, doing so requires a `version` to be set, which seems to be irrelevant since the version is already configured.

Seems like the two options for fixing this are to either (1) allow the entry in dependencies to be omit the version or (2) allow the entry in replacements to declare the library as visible.
