### ISSUE TITLE
Not finding a particular dependency that does exist

### ISSUE THREAD

**Issue by jasonrharris** [johnynek/bazel-deps#263]
With the following dependency file (note resolvers):
```
xoptions:
  buildHeader:
    - licenses(["notice"])
    - load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")
    - load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")
    - load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_import")
  thirdPartyDirectory: "third_party/jvm"
  languages: [ "java", "scala:2.12.6" ]
  resolverType: coursier
  resolvers:
    - id: "spring-repo"
      url: https://repo.spring.io/plugins-release/
  transitivity: runtime_deps
  versionConflictPolicy: highest

dependencies:
  net.swisstech:
    bitly-api-client:
      lang: "java"
      version: "0.8.0"
```

https://repo.spring.io/plugins-release/net/swisstech/bitly-api-client/0.8.0/ is not resolved:

```
[ForkJoinPool-1-worker-7] ERROR bazel_deps.CoursierResolver - not found: /Users/jasonharris/.ivy2/local/net.swisstech/bitly-api-client/0.8.0/ivys/ivy.xml
[ForkJoinPool-1-worker-7] ERROR bazel_deps.CoursierResolver - not found: http://central.maven.org/maven2/net/swisstech/bitly-api-client/0.8.0/bitly-api-client-0.8.0.pom
```

Other dependencies are resolved
