### ISSUE TITLE
"could not normalize versions"

### ISSUE THREAD

**Issue by nollbit** [johnynek/bazel-deps#27]
We're moving from many SBT projects to a single monorepo with Bazel. I'm in the midst of trying to figure out our dependencies.

We have `versionConflictPolicy: fixed`.

I'm getting the following message:
```
[ERROR] could not normalize versions:
io.netty:netty: Version(3.6.6.Final), Version(3.7.0.Final), Version(3.10.1.Final)
(snip)
```

I've tried fixing the netty version with 
```
dependencies:
  (snip)
  "io.netty":
    "netty":
      version: "3.10.1.Final"
      lang: "java"
  (snip)
```

However, I keep getting the version conflict. 

I've made sure that there are no other `io.netty` dependencies declared anywhere else in `dependencies.yaml`.

Is this a bug or am I simply missing something?
