### ISSUE TITLE
--disable-3rdparty-in-repo sometimes generates empty BUILD files for Kotlin deps

### ISSUE THREAD

**Issue by pbsf** [johnynek/bazel-deps#290]
I have the following dependencies.yaml:
```
options:
  buildHeader: [ "load(\"@io_bazel_rules_kotlin//kotlin:kotlin.bzl\", \"kt_jvm_import\")",
    "licenses([\"notice\"])" ]
  languages: [ "kotlin" ]
  resolverType: "coursier"
  resolvers:
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
  thirdPartyDirectory: "3rdparty"

dependencies:
  com.github.ajalt:
    clikt:
      lang: kotlin
      version: "2.3.0"
```

I modified `update_dependencies.sh` to receive `--disable-3rdparty-in-repo` as a flag.

The following works:
```
./update_dependencies.sh
bazel build //3rdparty/com/github/ajalt:clikt
```

The following doesn't:
```
./update_dependencies.sh --disable-3rdparty-in-repo
bazel build @3rdparty//3rdparty/com/github/ajalt:clikt
```

Here is the error message:
```
ERROR: no such target '@3rdparty//3rdparty/com/github/ajalt:clikt': target 'clikt' not declared in package '3rdparty/com/github/ajalt' defined by /root/.cache/bazel/_bazel_root/a254c33c1cf4cabb64a59c0bfb96da7c/external/3rdparty/3rdparty/com/github/ajalt/BUILD
```

Here is the content of the generated BUILD file on the second attempt:
```
 $ cat  /root/.cache/bazel/_bazel_root/a254c33c1cf4cabb64a59c0bfb96da7c/external/3rdparty/3rdparty/com/github/ajalt/BUILD
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_import")
licenses(["notice"])
```

I did succeed importing some Kotlin dependencies disabling the 3rd party folders, but not this one, which is weird. Is the second command incorrect? I can create a repository that reproduces the issue if that helps.
