### ISSUE TITLE
No BUILD files generated for a java dependency

### ISSUE THREAD

**Issue by avibryant** [johnynek/bazel-deps#303]
Using the following dependencies.yaml:

```yaml
options:
  languages: [ "java", "scala:2.12.14" ]
  resolvers:
    - id: "geotoolkit"
      type: "default"
      url: https://maven.geotoolkit.org
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
    - id: "osgeo"
      type: "default"
      url: https://repo.osgeo.org/repository/release/

dependencies:
  org.geotools:
    gt-geotiff:
      lang: java
      version: "25.2"
```

`update_dependencies.sh` successfully resolves the packages and writes out workspace.bzl, but despite its claim to have written 92 BUILD files, there are none in 3rdparty.
