### ISSUE TITLE
collapsing modules sometimes fails

### ISSUE THREAD

**Issue by johnynek** [johnynek/bazel-deps#35]
example from @ianoc

```
  org.apache.poi:
    poi:
      lang: java
    poi-ooxml:
      lang: java
    poi-ooxml-schemas:
      lang: java
```
as
```  org.apache.poi:
    poi:
      lang: java
      modules: [ "ooxml", "ooxml-schemas" ]
```
But then next time i run the tool it fails because the non-suffixed target isn’t included. Doing
```  org.apache.poi:
    poi:
      lang: java
      modules: [ "", "ooxml", "ooxml-schemas" ]
```
