### ISSUE TITLE
minimization in format has bugs.

### ISSUE THREAD

**Issue by johnynek** [johnynek/bazel-deps#44]
Examples:

```
-    bijection:
+    bijection-core:
       lang: scala
-      modules: [ "core", "macros" ]
       version: "0.9.2"
     bijection-json:
       exports:
@@ -167,15 +164,22 @@ dependencies:
         - "org.codehaus.jackson:jackson-mapper-asl"
       lang: scala
       version: "0.9.2"
+    bijection-macros:
+      lang: scala
+      version: "0.9.2"
```

Since we go through in order, the first one that fails to match makes a cut in the sorted order.

```
     chill:
       lang: scala
-      modules: [ "", "algebird", "bijection", "scrooge" ]
+      modules: [ "algebird", "bijection" ]
       version: "0.7.3"
-    chill-hadoop:
-      lang: java
+    chill-:
+      lang: scala
       version: "0.7.3"
-    chill-java:
+    chill:
       lang: java
+      modules: [ "hadoop", "java" ]
+      version: "0.7.3"
+    chill-scrooge:
+      lang: scala
       version: "0.7.3"
```
There are two bugs here: 1 the cut bug, 2 somehow `chill-` is showing up, but it should be just `chill`.

**Comment by mikemintz** [comment]
Another problematic example is

```
    util:
      lang: scala
      modules: [ "codec", "core", "stats" ]
      version: "6.26.0"
    util-cache:
      lang: scala
      version: "6.29.0"
    util-collection:
      lang: scala
      version: "6.29.0"
    util-events:
      lang: scala
      version: "6.29.0"
```

which gets rewritten to

```
    util:
      lang: scala
      modules: [ "codec", "core", "stats" ]
      version: "6.26.0"
    util-cache:
      lang: scala
      version: "6.29.0"
    util:
      lang: scala
      modules: [ "collection", "events" ]
      version: "6.29.0"
```

which is bad since `util` is duplicated.
