### ISSUE TITLE
Documentation request: How do I specify a resolver for a dependency?

### ISSUE THREAD

**Issue by seanmcl** [johnynek/bazel-deps#56]
I'm trying to use maven central for all dependences that live there, but jcenter for those that don't.  In `options` I have

```
options:
  ...
  resolvers:
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
    - id: "jcenter"
      type: "secondary"  # What are the legal types?
      url: https://jcenter.bintray.com/
  ...
```

but I don't know how to tell bazel-deps that a particular dep should use jcenter.  Currently, workspace.bzl is generated with all dependencies having resolver maven central, even though I get errors when running bazel.  One example is

```
  com.monsanto.arch:
    cloud-formation-template-generator:
      version: "3.5.2"
      lang: scala
```

This generates

```
    callback({"artifact": "com.monsanto.arch:cloud-formation-template-generator_2.12:3.5.2", "lang": "scala", "sha1": "096d8df8dbcf702413c1f8fea3a24314b5888979", "repository": "https://repo.maven.apache.org/maven2/", "name": "com_monsanto_arch_cloud_formation_template_generator_2_12", "actual": "@com_monsanto_arch_cloud_formation_template_generator_2_12//jar:file", "bind": "jar/com/monsanto/arch/cloud_formation_template_generator_2_12"})
```

I tried 

```
  com.monsanto.arch:
    cloud-formation-template-generator:
      version: "3.5.2"
      lang: scala
      resolver: jcenter
```

but that had no effect.  I grepped through the source code looking for where you look up the resolver, but couldn't figure it out. 

Thanks!
