### ISSUE TITLE
empty module name generates invalid dependencies.yaml after add-dep

### ISSUE THREAD

**Issue by kevingessner** [johnynek/bazel-deps#57]
Start with this dependencies.yaml:

```yaml
options:
  languages: [ "scala:2.11" ]
  resolvers:
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/

dependencies:
  com.twitter:
    finagle:
      lang: scala
      modules: [ "", "core" ]
      version: "6.43.0"
```

Run `gen_maven_deps.sh add-dep --deps dependencies.yaml --lang scala com.twitter:finagle-stats:6.43.0`

I'd expect that `"stats"` would be added to finagle's `modules`, but instead this invalid dependencies.yaml is produced:

```yaml
options:
  languages: [ "scala:2.11" ]
  resolvers:
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/

dependencies:
  com.twitter:
    finagle-:
      lang: scala
      version: "6.43.0"
    finagle:
      lang: scala
      modules: [ "core", "stats" ]
      version: "6.43.0"
```

The `finagle-` dependency is invalid, and breaks `generate`.  `format-deps` does not repair it.

(This is "bug 2" of number issue #44)
