### ISSUE TITLE
Take Maven coords instead of YAML

### ISSUE THREAD

**Issue by cgrushko** [johnynek/bazel-deps#61]
... well, maybe not instead, both support something like

```
dependencies:
  'javax.servlet:javax.servlet-api:jar:4.0.0'
```

Instead of 

```
dependencies:
  javax.servlet:
    javax.servlet-api:
      version: "4.0.0"
      lang: java
```
