### ISSUE TITLE
Optionally include the correct load statement for Scala files

### ISSUE THREAD

**Issue by greggdonovan** [johnynek/bazel-deps#86]
For build files that include a scala rule, include the correct `rules_scala` load statement. E.g. if the BUILD file includes a `scala_library` rule, insert `load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")` before the rules in that file.

This provides an option when you might not want to include `scala_library` in the prelude. See [discussion](https://github.com/bazelbuild/BUILD_file_generator/pull/23#discussion_r144666210).

**Comment by johnynek** [comment]
so, you want something here like language specific headers?

I think that should be fine.

something like:
```yaml
options:
  languageBuildHeaders:
    scala:
        - load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")
```
so we can group options per language?

Open to other suggestions.
